function options = temperature(options)
  options.temperatureOptions = Options( ...
    ... Primary
    'method', 'Analytical', ...
    'analysis', 'Transient', ...
    'modelOrderReduction', [], ...
    ... General
    'processorCount', options.processorCount, ...
    'floorplan', options.die.filename, ...
    'hotspotConfig', File.choose(options.assetPath, 'hotspot.config'), ...
    'samplingInterval', options.samplingInterval, ...
    'ambientTemperature', options.leakageOptions.parameters.T.range(1), ...
    'leakageOptions', options.leakageOptions, ...
    ... Static/Dynamic Steady-State
    'maximalTemperature', options.leakageOptions.parameters.T.range(2), ...
    'convergenceMetric', 'NRMSE', ...
    'convergenceTolerance', 0.01, ... % below 1 %
    'iterationLimit', 10, ...
    ... Dynamic Steady-State
    'algorithm', 'condensedEquationSingle', ...
    options.get('temperatureOptions', []));
end