function assessLinearLeakage(varargin)
  assess( ...
    Options( ...
       varargin{:}, ...
      'processParameters', { 'L' }, ...
      'temperatureOptions', Options( ...
        'analysis', 'DynamicSteadyState')), ...
    Options( ...
      'leakageOptions', Options( ...
        'dependency', 'Linear', ...
        'rangeConstraints', Options( ...
          'T', Utils.toKelvin([ 50, 100 ]), ...
          'L', 50e-9 + 0.05 * 22.5e-9 * [ -1, 1 ]))));
end
