function compare(varargin)
  assess( ...
    Options('algorithm', 1), ...
    Options('algorithm', 2), ...
    Options('temperatureOptions', Options( ...
      'analysis', 'DynamicSteadyState')));
end
