clear all;
setup;

dimensionCount = 2;
order = 5;

subplot(1, 2, 1);
color = Color.pick(1);

grid = Quadrature( ...
  'method', 'sparse', ...
  'dimensionCount', dimensionCount, ...
  'order', order, ...
  'ruleName', 'GaussHermiteHW');

plot(grid, 'Color', color, 'MarkerFaceColor', color, ...
  'Marker', 'o', 'MarkerSize', 5);
Plot.title('Sparse grid with %d nodes', grid.nodeCount);

subplot(1, 2, 2);
color = Color.pick(2);

grid = Quadrature( ...
  'method', 'tensor', ...
  'dimensionCount', dimensionCount, ...
  'order', order, ...
  'ruleName', 'GaussHermiteHW');

plot(grid, 'Color', color, 'MarkerFaceColor', color, ...
  'Marker', 'o', 'MarkerSize', 5);
Plot.title('Tensor grid with %d nodes', grid.nodeCount);