function display(this)
  options = Options( ...
    'Input dimension', this.inputCount, ...
    'Output dimension', this.outputCount, ...
    'Level', this.level, ...
    'Nodes', this.nodeCount, ...
    'Last nodes', this.levelNodeCount(end));
  display(options, 'Adaptive sparse grid collocation');
end
