function result = estimateCrossExpectation(basis, i1, j1, i2, j2)
  result = integral(@(Y) ...
    basis.evaluate(Y(:), i1, j1, ones(size(Y)).').' .* ...
    basis.evaluate(Y(:), i2, j2, ones(size(Y)).').', ...
    basis.support(1), basis.support(2));
end
