function save(filename, varargin)
  options = Options(varargin{:});

  set(gcf, ...
    'PaperType', 'A4', ...
    'PaperOrientation', options.get('orientation', 'landscape'), ...
    'PaperPositionMode', 'auto');

  print(filename, '-painters', ...
    ['-d', options.get('format', 'pdf')], ...
    ['-r', num2str(options.get('resolution', 400))]);
end
