function Hermite
  setup;

  pc = PolynomialChaos.Hermite( ...
    'inputCount', 1, ...
    'outputCount', 1, ...
    'order', 5, ...
    'quadratureOptions', Options( ...
      'method', 'tensor', ...
      'order', 10));
  plot(pc);
end
