function Hermite
  clear all;
  setup;

  chaos = PolynomialChaos.Hermite( ...
    'inputCount', 1, ...
    'outputCount', 1, ...
    'order', 5, ...
    'quadratureOptions', Options( ...
      'method', 'tensor', ...
      'order', 10));

  plot(chaos);
end
