function JacobiBeta11
  setup;

  order = 1;
  sampleCount = 1e5;

  f = @(x) x;

  distribution = ProbabilityDistribution.Beta( ...
    'alpha', 2, 'beta', 2, 'a', -1, 'b', 1);

  samples = distribution.sample(sampleCount, 1);

  mcData = f(samples);

  pc = PolynomialChaos.Jacobi( ...
    'order', order, ...
    'inputCount', 1, ...
    'outputCount', 1, ...
    'quadratureOptions', ...
      Options('method', 'tensor', 'order', 4), ...
    'alpha', distribution.alpha - 1, ...
    'beta', distribution.beta - 1, ...
    'a', distribution.a, ...
    'b', distribution.b);

  pcOutput = pc.expand(f);
  pcData = pc.evaluate(pcOutput, samples);

  assess(mcData, pc, pcData, pcOutput, distribution);
end
