function result = deriveCovariance(basis, i1, j1, i2, j2)
  result = call(basis, 'deriveCrossExpectation', i1, j1, i2, j2) - ...
    call(basis, 'deriveExpectation', i1, j1) * ...
    call(basis, 'deriveExpectation', i2, j2);
end
