function Step(varargin)
  setup;
  assess(@target, ...
    'maximalLevel', 20, ...
    'exactExpectation', 0.5, ...
    'exactVariance', 0.25, ...
    varargin{:});
end

function y = target(x)
  y = ones(size(x));
  y(x > 1/2) = 0;
end
