function JacobiGaussian
  setup;

  gaussian = ProbabilityDistribution.Gaussian( ...
    'mu', 0, 'sigma', 1);
  beta = ProbabilityDistribution.Beta( ...
    'alpha', 2, 'beta', 2, 'a', -1, 'b', 1);

  assess(@(x) gaussian.icdf(beta.cdf(x)), ...
    'basis', 'Jacobi', 'order', 10, ...
    'distribution', beta, ...
    'exact', gaussian);
end
