function JacobiBetaN1
  setup;

  assess(@(x) exp(prod(x, 2)), ...
    'basis', 'Jacobi', 'inputCount', 4, 'order', 7, ...
    'alpha', 1, 'beta', 1, 'a', -1, 'b', 1, ...
    'quadratureOptions', Options('method', 'sparse'));
end
