function plotPolynomialRegression(varargin)
  assess('leakageOptions', Options( ...
    'approximation', 'Regression.LogPolynomial', ...
    'termPowers', Options( ...
      'T',    [ 0, 0, 1, 1, 0, 1 ], ...
      'L', [ 0, 1, 0, 1, 2, 2 ]), ...
    'countConstraints', Options('T', 50, 'L', 50), ...
    'rangeConstraints', Options('T', Utils.toKelvin([ 40, 400 ]))), ...
    varargin{:});
end
