function plotLinearInterpolation(varargin)
  assess('leakageOptions', Options( ...
    'approximation', 'Interpolation.Linear', ...
    'countConstraints', Options('T', 50, 'Leff', 50), ...
    'rangeConstraints', Options('T', Utils.toKelvin([ 40, 400 ]))), ...
    varargin{:});
end
