function gaussianToBeta
  close all;
  setup;

  gaussian = ProbabilityDistribution.Gaussian( ...
    'mu', 0.5 * 50e-9, ...
    'sigma', sqrt(0.5) * 0.04 * 22.5e-9);

  beta = Utils.gaussianToBeta(gaussian, ...
    'target', 'variance', ...
    'a', 0.5 * 50e-9 - 3 * sqrt(0.5) * 0.04 * 22.5e-9, ...
    'b', 0.5 * 50e-9 + 3 * sqrt(0.5) * 0.04 * 22.5e-9);

  x = linspace(beta.a, beta.b, 50);
  f1 = gaussian.pdf(x);
  f2 = beta.pdf(x);

  Plot.figure;
  Plot.line(x, f1, 'number', 1, 'markEach', 2);
  Plot.line(x, f2, 'number', 2, 'markEach', 2);

  Plot.legend( ...
    sprintf('Gaussian (%s, %s^2)', num2str(gaussian.mu), ...
      num2str(gaussian.sigma)), ...
    sprintf('Beta (%s, %s, %s, %s)', num2str(beta.alpha), ...
      num2str(beta.beta), num2str(beta.a), num2str(beta.b)));
end
