function assessLinearLeakage(varargin)
  compare( ...
    Options(varargin{:}, ...
      'analysis', 'DynamicSteadyState', ...
      'processParameters', { 'L' }), ...
    Options('linearizeLeakage', Options( ...
      'T', Utils.toKelvin([ 50, 100 ]), ...
      'L', 50e-9 + 0.05 * 22.5e-9 * [ -1, 1 ])));
end
