function options = reliabilityAnalysis(varargin)
  options = Options(varargin{:});

  options.fatigueOptions = Options( ...
    'mechanism', 'ThermalCycling', ...
    'samplingInterval', options.samplingInterval, ...
    options.get('fatigueOptions', []));
end