function options = leakagePower(options)
  leakageParameters = Options;

  leakageParameters.add('T', struct( ...
    'nominal', Utils.toKelvin(85), ...
    'range', Utils.toKelvin([45, 450]), ...
    'reference', Utils.toKelvin(150)));
  leakageParameters.update(options.processParameters);

  options.leakageOptions = Options( ...
    'method', 'Interpolation.Linear', ...
    'circuit', Circuit('name', 'ring_nangate_HP', ...
      'parameters', leakageParameters), ...
    'parameters', leakageParameters, ...
    'referencePower', 0.4 / (1 - 0.4) * options.platform.computeAveragePower, ...
    options.get('leakageOptions', []));
end