function plot(this)
  [ L, T ] = meshgrid( ...
    linspace(this.LRange(1), this.LRange(2), 50), ...
    linspace(this.TRange(1), this.TRange(2), 50));

  I = this.evaluate(this.output, L, T);

  figure;
  line(L, Utils.toCelsius(T), I, ...
    'LineStyle', 'None', ...
    'Marker', 'o', ...
    'MarkerEdgeColor', 'w', ...
    'MarkerFaceColor', 'b');

  Plot.title('Leakage current');
  Plot.label('Channel length, m', 'Temperature, C', ...
    'Leakage current, A');

  grid on;
  view(10, 10);
end
