function CustomRegression(varargin)
  assess('leakageOptions', Options( ...
    'dependency', 'Linear', 'rangeConstraints', Options( ...
      'T', Utils.toKelvin([ 50, 100 ]), ...
      'L', 50e-9 + 0.05 * 22.5e-9 * [ -1, 1 ])), ...
    varargin{:});
end
