function LogPolynomialRegression(varargin)
  assess('processParameters', { 'L' }, 'leakageOptions', Options( ...
    'method', 'Regression', 'basis', 'LogPolynomial', ...
    'termPowers', Options( ...
      'T', [ 0, 0, 1, 1, 0, 1 ], ...
      'L', [ 0, 1, 0, 1, 2, 2 ])), ...
    varargin{:});
end
