function compare(varargin)
  setup;

  one = 'MonteCarlo';
  two = 'PolynomialChaos';

  options = Configure.systemSimulation(varargin{:});
  options = Configure.deterministicAnalysis(options);
  options = Configure.stochasticAnalysis(options);

  timeSlice = options.stepCount * options.samplingInterval / 2;
  k = floor(timeSlice / options.samplingInterval);

  [ ~, oneStats, oneOutput ] = construct(options, 'surrogate', one);
  [ ~, twoStats, twoOutput ] = construct(options, 'surrogate', two);

  Plot.temperatureVariation( ...
    { oneStats.expectation, twoStats.expectation }, ...
    { oneStats.variance, twoStats.variance }, ...
    'time', options.timeLine, 'names', { one, two });

  Statistic.compare( ...
    Utils.toCelsius(oneOutput.data(:, :, k)), ...
    Utils.toCelsius(twoOutput.data(:, :, k)), ...
    'method', 'smooth', 'range', 'unbounded', ...
    'layout', 'one', 'draw', true, ...
    'names', { one, two });

  Statistic.compare( ...
    Utils.toCelsius(oneOutput.data), ...
    Utils.toCelsius(twoOutput.data), ...
    'method', 'histogram', 'range', 'unbounded', ...
    'layout', 'separate', 'draw', true, ...
    'names', { one, two });
end
