function assessLinearLeakage(varargin)
  compare( ...
    Options(varargin{:}, 'method', 'MonteCarlo'), ...
    Options('linearizeLeakage', Options( ...
      'VRange', 45e-9 + 0.05 * 45e-9 * [ -1, 1 ], ...
      'TRange', Utils.toKelvin([ 50, 100 ]))));
end
