function name = leakageParameterDataFile(varargin)
  options = Options(varargin{:});
  name = File.join(File.library('ElectronicSystems', ...
    'CircuitSimulation'), 'Circuits', [ String.join('_', 'parameters', ...
      Name.parameters(options.leakageParameters)), '.txt' ]);
end