function additive
  close all;
  setup;

  inputCount = 2;
  f = @(u) sum(u.^2, 2);

  assess(f, ...
    'inputCount', inputCount, ...
    'control', 'InfNorm', ...
    'tolerance', 1e-2, ...
    'maximalLevel', 20, ...
    'exactExpectation', inputCount / 3, ...
    'exactVariance', inputCount * 4 / 45);
end
