function assessAdditive
  setup;
  inputCount = 2;
  assess(@(u) sum(u.^2, 2), ...
    'inputCount', inputCount, ...
    'exactExpectation', inputCount / 3, ...
    'exactVariance', inputCount * 4 / 45);
end
