function options = ASGC(varargin)
  options = Options(varargin{:});

  options.surrogateOptions = Options( ...
    'control', 'InfNormSurpluses', ...
    'tolerance', 1e-2, ...
    'maximalLevel', 6, ...
    'verbose', true);
end
