function display(this)
  options = Options( ...
    'Input dimension', this.inputDimension, ...
    'Output dimension', this.outputDimension, ...
    'Polynomial order', this.order, ...
    'Polynomial terms', size(this.coefficients, 1), ...
    'Monomial terms', size(this.rvPower, 1));
  display(options, 'Polynomial chaos');
end
