function display(this)
  options = Options( ...
    'Input dimension', this.inputCount, ...
    'Polynomial order', this.order, ...
    'Polynomial terms', this.termCount, ...
    'Monomial terms', size(this.rvPower, 1), ...
    'Quadrature nodes', this.nodeCount);
  display(options, 'Polynomial chaos');
end
